name: l3_flutter_selise_blocksconstruct
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.5.2

  #routing
  go_router: ^14.8.0
  go_router_builder: ^2.8.0

  #state_management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  #network
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.0

  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3

  #animations
  lottie: ^3.1.0
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  reactive_forms: ^17.0.1

  intl_phone_field: ^3.1.0
  pinput: ^5.0.1
  image_picker: ^1.1.2

  fl_chart: ^0.70.2
  local_auth: ^2.3.0
  web_socket_channel: ^3.0.3


dev_dependencies:
  #dart run change_app_package_name:main com.new.package.name
  build_runner: ^2.4.15
  change_app_package_name: ^1.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.4

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lottie/
    - environments/

  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Black.otf
