name: Sonar quality check


on:
  pull_request:
    branches: [ "stage" ]
    types:
      - closed


env:
  RUN_SONARQUBE: 'true'

jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      envvalue1: ${{ steps.setvar.outputs.envvar1 }}
    steps:
      - name: set value
        id: setvar
        run: |
          echo envvar1="$RUN_SONARQUBE" >> $GITHUB_OUTPUT

  sonarqube-job:
    if: ${{ success() && needs.initialization.outputs.envvalue1=='true' }}
    uses: ./.github/workflows/2_sonar.yml
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
    needs: [initialization]


